application:
  subdomain: bark-server
  background_task: true
  injects:
    - id: redirect-404-to-help
      on: response
      auth_required: false
      when:
        - "/*"
      do: |
        if (ctx.status === 404) {
          ctx.response.send(302, "", { location: "/help" });
          return;
        }
  entries:
    - id: help
      title: "使用帮助"
      path: /help
    - id: main
      title: "Bark Server"
      path: /

  public_path:
    - /
    - /help

  upstreams:
    - location: /help
      backend: file:///lzcapp/pkg/content/tours.html
    - location: /
      backend: http://bark-server:8080/

services:
  bark-server:
    # ghcr.io/finb/bark-server:v2.3.5
    image: registry.lazycat.cloud/czyt/finb/bark-server:b403b21abb2bc421
    entrypoint: /bin/sh
    command: /lzcapp/pkg/content/startup.sh
    environment:
      - HELP_URL=/help
    binds:
      - /lzcapp/var/data:/data

usage: "请打开应用的“使用帮助”入口，或通过应用域名的 /help 路径查看 Bark Server 使用说明。"
